version: '3'
services:
  mysql8:
    image: mysql:8
    env_file:
      - settings
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf:ro  # only in this way could change default auth plugin!
      - type: volume
        source: db-volume
        target: /mnt/db-data
        volume:
          nocopy: true
volumes:
  db-volume:
    driver_opts:
      type: "nfs"
      o: "addr=10.206.16.4,nolock,soft,rw"
      device: ":/ljvuvwv7"